### ISSUE TITLE
Dummy Data Selection for Testing

### ISSUE THREAD

**Issue by LisaSeq** [UBC-MDS/simpute-py#18]
For Milestone 2 we will need a dummy data file to use for all testing.

**Comment by renee-kwon** [comment]
I found this dataset that includes boolean, categorical, numerical, and date data... I will clean it up a little bit, add null values, and upload it for use. https://www.kaggle.com/datasets/thedevastator/tesla-accident-fatalities-analysis-and-statistic?resource=download

**Comment by renee-kwon** [comment]
Hello team, I've added our dummy data into the [tests](https://github.com/UBC-MDS/simpute-py/tree/master/tests) folder - tesla_deaths.csv.

Columns: 
**Date** - date of the accident 
**Continent** - continent accident occurred in **(categorical column - 10 null values)**
**Country** - country accident occurred in 
**Deaths** - how many people died in the accident **(numerical column - 10 null values)**
**Driver** - whether or not the driver of the Tesla vehicle died **(boolean column - 10 null values)**
**Description** - description of the accident
**Source** - article of accident

![tesla_deaths csv(1)](https://user-images.githubusercontent.com/112587916/213636843-99e99c84-36dc-409d-8dcc-9d2eec906b94.png) ![tesla_deaths csv(2)](https://user-images.githubusercontent.com/112587916/213636851-ed361597-cd7c-49f3-9321-c34a383d1964.png)

Thank you
