### ISSUE TITLE
January 17 Lab - Meeting Minutes

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/simpute-py#19]
We went over milestone 2 guidelines and discussed our next steps. 

Discussions: 
- Separating script file using separate branches
- Writing unit tests for each function
- Finding a dummy data file for test functions (Renee)
- Usage of project board and assigning of tasks 

We will meet again on Thursday to finalize our week's tasks.

**Comment by LisaSeq** [comment]
Tasks assigned in other issues.
