### ISSUE TITLE
Team Work Contract

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/simpute-py#2]
Hello @LisaSeq @kenuiuc @Althrun-sun 

I've drafted a team contract [here](https://docs.google.com/document/d/1flsLddYatXaquuB7HzFSfGRYT5zO7YWc_FAyXvSxN1I/edit) - please comment here if you have any suggestions/changes you'd like to make or if you approve!

Thanks, 

Renee

**Comment by kenuiuc** [comment]
@renee-kwon 
Looks Good To Me. Thank you!

**Comment by LisaSeq** [comment]
@renee-kwon same here!
