### ISSUE TITLE
January 19 Meeting Minutes

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/simpute-py#21]
**January 19 - Meeting Minutes**

Today we discussed that we will need users to specify which column they would like considered as a categorical variable. 

There is no way to decipher what is text and what is categorical data otherwise. 

We will add a new argument for all our functions and the columns that do not fit into boolean data, numerical data, categorical data (user specified) will not be considered into our kNN model used for imputation. 

Tasks 

Lisa:
- [x] update readme with necessary arguments 
- [x] update docstrings in our script file

Thank you,

**Comment by LisaSeq** [comment]
Both tasks completed. @kenuiuc  needs to complete and update the README for his Date imputer, but all others are done.

**Comment by renee-kwon** [comment]
I updated the readme since we are using median point of dates. Completed
